[build]
  base = "Back-End"
  command = "flutter build web --release"
  publish = "Back-End/build/web"

[build.environment]
  FLUTTER_VERSION = ">=3.7.0 <4.0.0"
  NODE_VERSION = "18"
  TZ = "Asia/Manila"

[[plugins]]
  package = "netlify-plugin-flutter"
